services:
  postgres:
    container_name: postgres
    image: postgres:18
    environment:
        POSTGRES_DB: ${DB_NAME}
        POSTGRES_USER: ${DB_USER}
        POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
    - "postgres-data:/var/lib/postgresql" 
    ports:
    - "${DB_PORT}:5432"
  shabasher:
    build:
      context: ../..
      dockerfile: Shabasher/Shabasher.API/Dockerfile
    ports:
      - "5000:5000"
    container_name: shabasher
    environment:
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT:-Development}
      - ASPNETCORE_URLS=http://0.0.0.0:5000
      - DB_CONNECTION_STRING=Host=postgres;Port=5432;Database=${DB_NAME:-shabasher_db};Username=${DB_USER:-postgres};Password=${DB_PASSWORD:-123123123}
      - JWT_SECRET=${JWT_SECRET}
      - JWT_HOURS=${JWT_HOURS:-12}
    depends_on:
    - postgres
  migrations: 
    build:
      context: ../..
      dockerfile: Shabasher/Shabasher.API/Dockerfile
    command: ["dotnet", "ef", "database", "update"]
    depends_on:
    - postgres
    environment:
     - DB_CONNECTION_STRING=Host=postgres;Port=5432;Database=${DB_NAME:-shabasher_db};Username=${DB_USER:-postgres};Password=${DB_PASSWORD:-123123123}
volumes:
  postgres-data: